
/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER.
 */

#ifndef _HEAVYCONTEXT_BASS_H_
#define _HEAVYCONTEXT_BASS_H_

#include "HvBase.h"

#define Context(_x) ((Hv_bass *) (_x))

// object includes
#include "SignalVar.h"
#include "ControlCast.h"
#include "ControlSlice.h"
#include "SignalLine.h"
#include "HeavyMath.h"
#include "ControlBinop.h"
#include "ControlVar.h"
#include "ControlDelay.h"
#include "SignalPhasor.h"
#include "ControlPack.h"

typedef struct Hv_bass {
  HvBase base;

  // objects
  SignalPhasor sPhasor_J1atb;
  SignalLine sLine_23sUO;
  SignalVarf sVarf_TAgzz;
  SignalPhasor sPhasor_tdyEe;
  SignalVarf sVarf_pmUtR;
  SignalVarf sVarf_kDRrV;
  SignalPhasor sPhasor_whoyy;
  SignalVarf sVarf_LHUtx;
  ControlBinop cBinop_EQjw5;
  ControlVar cVar_AoLoO;
  ControlDelay cDelay_uc5P0;
  ControlVar cVar_l34cn;
  ControlVar cVar_5FvbX;
  ControlVar cVar_atpMc;
  ControlPack cPack_g7yXB;
  ControlBinop cBinop_S0fNl;
  ControlBinop cBinop_eXMgi;
  ControlBinop cBinop_596bd;
  ControlBinop cBinop_hPgEc;
  ControlBinop cBinop_vohav;
  ControlSlice cSlice_ZhIzC;
  ControlSlice cSlice_UFPTf;
  ControlSlice cSlice_aXfdI;
  ControlSlice cSlice_kKB6R;
  ControlSlice cSlice_GQwCn;
} Hv_bass;

#endif // _HEAVYCONTEXT_BASS_H_
