
/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER.
 */

/*
 * System Includes
 */

#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "Heavy_bass.h"
#include "HvContext_bass.h"
#include "HeavyMath.h"


/*
 * Function Declarations
 */
static void cBinop_EQjw5_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_AoLoO_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_3Ptlv_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_u6Edv_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_uc5P0_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_XxFae_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_6GJfG_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cMsg_qgS8I_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_DO0WL_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_l34cn_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_1CLcH_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_beMsr_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_smwfQ_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cVar_5FvbX_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_atpMc_sendMessage(HvBase *, int, const HvMessage *const);
static void cPack_g7yXB_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_dvs5S_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_ZPoi2_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_S0fNl_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_eXMgi_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_596bd_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_hPgEc_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_j3b5V_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_jUpUK_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_GIudy_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_QXiLh_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_7rw8q_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_W1CVd_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_vohav_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_ZhIzC_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_UFPTf_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_aXfdI_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_kKB6R_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_GQwCn_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_sfOWA_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_ZfUra_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(
    HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {
    case 0x18EDF2BD: { // w_amt
      ctx_scheduleMessage(_c, m, &cReceive_W1CVd_sendMessage, 0);
      break;
    }
    case 0x67E37CA3: { // __hv_notein
      ctx_scheduleMessage(_c, m, &cReceive_sfOWA_sendMessage, 0);
      break;
    }
    case 0x5B29CFE0: { // w_freq
      ctx_scheduleMessage(_c, m, &cReceive_GIudy_sendMessage, 0);
      break;
    }
    case 0x811CC33F: { // gain
      ctx_scheduleMessage(_c, m, &cReceive_7rw8q_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static struct HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {
    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

Hv_bass *hv_bass_new_with_pool(double sampleRate, int poolKb) {
  hv_assert(sampleRate > 0.0); // can't initialise with sampling rate of 0
  hv_assert(poolKb >= 1); // a message pool of some reasonable size is always needed
  Hv_bass *const _c = (Hv_bass *) hv_malloc(sizeof(Hv_bass));

  Base(_c)->numInputChannels = 0;
  Base(_c)->numOutputChannels = 2;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, poolKb);
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;
  Base(_c)->name = "bass";

  Base(_c)->numBytes = sizeof(Hv_bass);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_J1atb, 0.0f, sampleRate);
  Base(_c)->numBytes += sLine_init(&_c->sLine_23sUO);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_TAgzz, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_tdyEe, 0.0f, sampleRate);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_pmUtR, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_kDRrV, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_whoyy, 0.0f, sampleRate);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_LHUtx, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_AoLoO, 10.0f);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_uc5P0, 10.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_l34cn, 1.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_5FvbX, 10.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_atpMc, 500.0f);
  Base(_c)->numBytes += cPack_init(&_c->cPack_g7yXB, 2);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_hPgEc, 1.0f); // __pow
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_ZhIzC, 0, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_UFPTf, 1, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_aXfdI, 3, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_kKB6R, 2, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_GQwCn, 4, 1);

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_u6Edv_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_ZfUra_sendMessage, 0);

  return _c;
}

Hv_bass *hv_bass_new(double sampleRate) {
  return hv_bass_new_with_pool(sampleRate, 10); // default to 10KB MessagePool
}

void hv_bass_free(Hv_bass *_c) {
  cPack_free(&_c->cPack_g7yXB);

  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}



/*
 * Static Function Implementation
 */
static void cBinop_EQjw5_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_pmUtR, m);
  cMsg_jUpUK_sendMessage(_c, 0, m);
}

static void cVar_AoLoO_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cPack_onMessage(_c, &Context(_c)->cPack_g7yXB, 1, m, &cPack_g7yXB_sendMessage);
}

static void cCast_3Ptlv_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_DO0WL_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_atpMc, 0, m, &cVar_atpMc_sendMessage);
}

static void cLoadbang_u6Edv_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_AoLoO, 0, m, &cVar_AoLoO_sendMessage);
}

static void cDelay_uc5P0_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_uc5P0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_l34cn, 0, m, &cVar_l34cn_sendMessage);
}

static void cCast_XxFae_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_uc5P0, 0, m, &cDelay_uc5P0_sendMessage);
}

static void cSwitchcase_6GJfG_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x7A5B032D: { // "stop"
      cMsg_qgS8I_sendMessage(_c, 0, m);
      break;
    }
    default: {
      cMsg_qgS8I_sendMessage(_c, 0, m);
      cDelay_onMessage(_c, &Context(_c)->cDelay_uc5P0, 1, m, &cDelay_uc5P0_sendMessage);
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_XxFae_sendMessage);
      break;
    }
  }
}

static void cMsg_qgS8I_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "clear");
  cDelay_onMessage(_c, &Context(_c)->cDelay_uc5P0, 0, m, &cDelay_uc5P0_sendMessage);
}

static void cMsg_DO0WL_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "stop");
  cSwitchcase_6GJfG_onMessage(_c, NULL, 0, m, NULL);
}

static void cVar_l34cn_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cPack_onMessage(_c, &Context(_c)->cPack_g7yXB, 0, m, &cPack_g7yXB_sendMessage);
}

static void cMsg_1CLcH_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  msg_setElementToFrom(m, 1, n, 0);
  sLine_onMessage(_c, &Context(_c)->sLine_23sUO, 0, m, NULL);
}

static void cCast_beMsr_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_3Ptlv_sendMessage);
}

static void cSwitchcase_smwfQ_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_beMsr_sendMessage);
      break;
    }
    default: {
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_dvs5S_sendMessage);
      break;
    }
  }
}

static void cVar_5FvbX_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_1CLcH_sendMessage(_c, 0, m);
}

static void cVar_atpMc_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_ZPoi2_sendMessage(_c, 0, m);
}

static void cPack_g7yXB_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sLine_onMessage(_c, &Context(_c)->sLine_23sUO, 0, m, NULL);
}

static void cCast_dvs5S_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSwitchcase_6GJfG_onMessage(_c, NULL, 0, m, NULL);
  cVar_onMessage(_c, &Context(_c)->cVar_5FvbX, 0, m, &cVar_5FvbX_sendMessage);
}

static void cMsg_ZPoi2_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.0f);
  msg_setElementToFrom(m, 1, n, 0);
  sLine_onMessage(_c, &Context(_c)->sLine_23sUO, 0, m, NULL);
}

static void cBinop_S0fNl_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 12.0f, 0, m, &cBinop_eXMgi_sendMessage);
}

static void cBinop_eXMgi_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_hPgEc, HV_BINOP_POW, 1, m, &cBinop_hPgEc_sendMessage);
  cMsg_j3b5V_sendMessage(_c, 0, m);
}

static void cBinop_596bd_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_J1atb, 0, m);
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_whoyy, 0, m);
}

static void cBinop_hPgEc_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 440.0f, 0, m, &cBinop_596bd_sendMessage);
}

static void cMsg_j3b5V_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 2.0f);
  cBinop_onMessage(_c, &Context(_c)->cBinop_hPgEc, HV_BINOP_POW, 0, m, &cBinop_hPgEc_sendMessage);
}

static void cMsg_jUpUK_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  msg_setElementToFrom(m, 1, n, 0);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 0.0f, 0, m, &cBinop_vohav_sendMessage);
}

static void cReceive_GIudy_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_tdyEe, 0, m);
}

static void cMsg_QXiLh_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.5f);
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_whoyy, 1, m);
}

static void cReceive_7rw8q_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_TAgzz, m);
  sVarf_onMessage(_c, &Context(_c)->sVarf_LHUtx, m);
}

static void cReceive_W1CVd_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 0.5f, 0, m, &cBinop_EQjw5_sendMessage);
}

static void cBinop_vohav_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_kDRrV, m);
}

static void cSlice_ZhIzC_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cSwitchcase_smwfQ_onMessage(_c, NULL, 0, m, NULL);
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_UFPTf_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 69.0f, 0, m, &cBinop_S0fNl_sendMessage);
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_aXfdI_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_kKB6R_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_GQwCn_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cReceive_sfOWA_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSlice_onMessage(_c, &Context(_c)->cSlice_GQwCn, 0, m, &cSlice_GQwCn_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_aXfdI, 0, m, &cSlice_aXfdI_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_kKB6R, 0, m, &cSlice_kKB6R_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_UFPTf, 0, m, &cSlice_UFPTf_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_ZhIzC, 0, m, &cSlice_ZhIzC_sendMessage);
}

static void cLoadbang_ZfUra_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_QXiLh_sendMessage(_c, 0, m);
}




/*
 * Context Process Implementation
 */

int hv_bass_process(Hv_bass *const _c, float **const inputBuffers, float **const outputBuffers, int nx) {
  const int n4 = nx & ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD

  // temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4, Bf5, Bf6;

  // input and output vars
  hv_bufferf_t O0, O1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; __hv_zero_f(VOf(ZERO));

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  for (int n = 0; n < n4; n += HV_N_SIMD) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

    

    // zero output buffers
    __hv_zero_f(VOf(O0));
    __hv_zero_f(VOf(O1));

    // process all signal functions
    __hv_phasor_k_f(&_c->sPhasor_J1atb, VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_k_f(VOf(Bf0), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf0));
    __hv_mul_f(VIf(Bf1), VIf(Bf0), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf3), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf4), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_sub_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_fma_f(VIf(Bf0), VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_line_f(&_c->sLine_23sUO, VOf(Bf3));
    __hv_mul_f(VIf(Bf4), VIf(Bf3), VOf(Bf4));
    __hv_var_f(&_c->sVarf_TAgzz, VOf(Bf0));
    __hv_mul_f(VIf(Bf4), VIf(Bf0), VOf(Bf0));
    __hv_phasor_k_f(&_c->sPhasor_tdyEe, VOf(Bf4));
    __hv_var_k_f(VOf(Bf1), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf4), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_k_f(VOf(Bf4), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf1), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf4), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf4));
    __hv_mul_f(VIf(Bf1), VIf(Bf4), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf5), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf6), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf6), VOf(Bf6));
    __hv_sub_f(VIf(Bf1), VIf(Bf6), VOf(Bf6));
    __hv_fma_f(VIf(Bf4), VIf(Bf5), VIf(Bf6), VOf(Bf6));
    __hv_var_f(&_c->sVarf_pmUtR, VOf(Bf5));
    __hv_var_f(&_c->sVarf_kDRrV, VOf(Bf4));
    __hv_fma_f(VIf(Bf6), VIf(Bf5), VIf(Bf4), VOf(Bf4));
    __hv_mul_f(VIf(Bf0), VIf(Bf4), VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(O0), VOf(O0));
    __hv_phasor_k_f(&_c->sPhasor_whoyy, VOf(Bf0));
    __hv_var_k_f(VOf(Bf5), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf5), VOf(Bf5));
    __hv_abs_f(VIf(Bf5), VOf(Bf5));
    __hv_var_k_f(VOf(Bf0), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf5), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf5), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf5), VOf(Bf5));
    __hv_mul_f(VIf(Bf5), VIf(Bf5), VOf(Bf0));
    __hv_mul_f(VIf(Bf5), VIf(Bf0), VOf(Bf6));
    __hv_mul_f(VIf(Bf6), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf2), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf6), VIf(Bf2), VOf(Bf2));
    __hv_sub_f(VIf(Bf5), VIf(Bf2), VOf(Bf2));
    __hv_fma_f(VIf(Bf0), VIf(Bf1), VIf(Bf2), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_LHUtx, VOf(Bf2));
    __hv_mul_f(VIf(Bf3), VIf(Bf2), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_add_f(VIf(Bf4), VIf(O1), VOf(O1));

    // save output vars to output buffer
    __hv_store_f(outputBuffers[0]+n, VIf(O0));
    __hv_store_f(outputBuffers[1]+n, VIf(O1));
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n4; // return the number of frames processed
}

int hv_bass_process_inline(Hv_bass *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  int n = hv_bass_process(c, bIn, bOut, n4);
  return n;
}

int hv_bass_process_interleaved(Hv_bass *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = inputBuffers[i+numChannels*j];
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_bass_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = bOut[i*n4+j];
    }
  }

  return n;
}

int hv_bass_process_interleaved_short(Hv_bass *const c, short *const inputBuffers, short *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = ((float) inputBuffers[i+numChannels*j]) * 0.00003051757813f;
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_bass_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = (short) (bOut[i*n4+j] * 32767.0f);
    }
  }

  return n;
}
