
/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER.
 */

/*
 * System Includes
 */

#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "Heavy_slot0.h"
#include "HvContext_slot0.h"
#include "HeavyMath.h"


/*
 * Function Declarations
 */
static void cCast_nF7qb_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_wVKMF_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_e57E3_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_aDUHx_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_vtAOk_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_3Zgtw_sendMessage(HvBase *, int, const HvMessage *const);
static void cUnop_4OB5u_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_5s7Ii_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_PijWF_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_kHPtR_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_7no2o_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_Yu3YO_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cLoadbang_nrj1W_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_eacHx_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_T5q1x_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_kkkKn_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_ZpZIH_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_JzxNw_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_A4ucb_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_3JGoR_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_kL7Y1_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_Ns8V7_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(
    HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {
    case 0x47593226: { // #HV_IN
      ctx_scheduleMessage(_c, m, &cReceive_Ns8V7_sendMessage, 0);
      break;
    }
    case 0x811CC33F: { // gain
      ctx_scheduleMessage(_c, m, &cReceive_PijWF_sendMessage, 0);
      break;
    }
    case 0x35FCD07D: { // pan
      ctx_scheduleMessage(_c, m, &cReceive_aDUHx_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static struct HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {
    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

Hv_slot0 *hv_slot0_new_with_pool(double sampleRate, int poolKb) {
  hv_assert(sampleRate > 0.0); // can't initialise with sampling rate of 0
  hv_assert(poolKb >= 1); // a message pool of some reasonable size is always needed
  Hv_slot0 *const _c = (Hv_slot0 *) hv_malloc(sizeof(Hv_slot0));

  Base(_c)->numInputChannels = 0;
  Base(_c)->numOutputChannels = 2;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, poolKb);
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;
  Base(_c)->name = "slot0";

  Base(_c)->numBytes = sizeof(Hv_slot0);
  Base(_c)->numBytes += sLine_init(&_c->sLine_jF2jq);
  Base(_c)->numBytes += sPhasor_init(&_c->sPhasor_G9l1w, sampleRate);
  Base(_c)->numBytes += sLine_init(&_c->sLine_O7R26);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_7hiGi, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_mEhBS, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_SSqFv, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_kkkKn, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_ZpZIH, 500.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_3JGoR, 0.0f); // __mul

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_nrj1W_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_e57E3_sendMessage, 0);

  return _c;
}

Hv_slot0 *hv_slot0_new(double sampleRate) {
  return hv_slot0_new_with_pool(sampleRate, 10); // default to 10KB MessagePool
}

void hv_slot0_free(Hv_slot0 *_c) {

  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}



/*
 * Static Function Implementation
 */
static void cCast_nF7qb_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_5s7Ii_sendMessage(_c, 0, m);
  cMsg_kHPtR_sendMessage(_c, 0, m);
  cMsg_wVKMF_sendMessage(_c, 0, m);
}

static void cMsg_wVKMF_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 150.0f);
  sLine_onMessage(_c, &Context(_c)->sLine_jF2jq, 0, m, NULL);
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 20.0f);
  msg_setFloat(m, 1, 150.0f);
  sLine_onMessage(_c, &Context(_c)->sLine_jF2jq, 0, m, NULL);
}

static void cLoadbang_e57E3_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSwitchcase_Yu3YO_onMessage(_c, NULL, 0, m, NULL);
}

static void cReceive_aDUHx_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 1.5708f, 0, m, &cBinop_vtAOk_sendMessage);
}

static void cBinop_vtAOk_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cUnop_onMessage(_c, HV_UNOP_COS, m, &cUnop_4OB5u_sendMessage);
  cUnop_onMessage(_c, HV_UNOP_SIN, m, &cUnop_3Zgtw_sendMessage);
}

static void cUnop_3Zgtw_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_SSqFv, m);
}

static void cUnop_4OB5u_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_mEhBS, m);
}

static void cMsg_5s7Ii_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.75f);
  sPhasor_onMessage(_c, &Context(_c)->sPhasor_G9l1w, 1, m);
}

static void cReceive_PijWF_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_7hiGi, m);
}

static void cMsg_kHPtR_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  sLine_onMessage(_c, &Context(_c)->sLine_O7R26, 0, m, NULL);
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.0f);
  msg_setFloat(m, 1, 150.0f);
  sLine_onMessage(_c, &Context(_c)->sLine_O7R26, 0, m, NULL);
}

static void cBinop_7no2o_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_kkkKn, 2, m, &cDelay_kkkKn_sendMessage);
}

static void cSwitchcase_Yu3YO_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cMsg_T5q1x_sendMessage(_c, 0, m);
      break;
    }
    case 0x7A5B032D: { // "stop"
      cMsg_T5q1x_sendMessage(_c, 0, m);
      break;
    }
    default: {
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_eacHx_sendMessage);
      break;
    }
  }
}

static void cLoadbang_nrj1W_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_JzxNw_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_ZpZIH, 0, m, &cVar_ZpZIH_sendMessage);
}

static void cCast_eacHx_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_T5q1x_sendMessage(_c, 0, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_kkkKn, 0, m, &cDelay_kkkKn_sendMessage);
  cMsg_5s7Ii_sendMessage(_c, 0, m);
  cMsg_kHPtR_sendMessage(_c, 0, m);
  cMsg_wVKMF_sendMessage(_c, 0, m);
}

static void cMsg_T5q1x_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "clear");
  cDelay_onMessage(_c, &Context(_c)->cDelay_kkkKn, 0, m, &cDelay_kkkKn_sendMessage);
}

static void cDelay_kkkKn_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_kkkKn, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_kkkKn, 0, m, &cDelay_kkkKn_sendMessage);
  cMsg_5s7Ii_sendMessage(_c, 0, m);
  cMsg_kHPtR_sendMessage(_c, 0, m);
  cMsg_wVKMF_sendMessage(_c, 0, m);
}

static void cVar_ZpZIH_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_3JGoR, HV_BINOP_MULTIPLY, 0, m, &cBinop_3JGoR_sendMessage);
}

static void cMsg_JzxNw_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_A4ucb_sendMessage);
}

static void cSystem_A4ucb_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_kL7Y1_sendMessage);
}

static void cBinop_3JGoR_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MAX, 1.0f, 0, m, &cBinop_7no2o_sendMessage);
}

static void cBinop_kL7Y1_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_3JGoR, HV_BINOP_MULTIPLY, 1, m, &cBinop_3JGoR_sendMessage);
}

static void cReceive_Ns8V7_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_5s7Ii_sendMessage(_c, 0, m);
  cMsg_kHPtR_sendMessage(_c, 0, m);
  cMsg_wVKMF_sendMessage(_c, 0, m);
}




/*
 * Context Process Implementation
 */

int hv_slot0_process(Hv_slot0 *const _c, float **const inputBuffers, float **const outputBuffers, int nx) {
  const int n4 = nx & ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD

  // temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4;

  // input and output vars
  hv_bufferf_t O0, O1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; __hv_zero_f(VOf(ZERO));

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  for (int n = 0; n < n4; n += HV_N_SIMD) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

    

    // zero output buffers
    __hv_zero_f(VOf(O0));
    __hv_zero_f(VOf(O1));

    // process all signal functions
    __hv_line_f(&_c->sLine_jF2jq, VOf(Bf0));
    __hv_phasor_f(&_c->sPhasor_G9l1w, VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_k_f(VOf(Bf0), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf0));
    __hv_mul_f(VIf(Bf1), VIf(Bf0), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf3), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf4), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_sub_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_fma_f(VIf(Bf0), VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_line_f(&_c->sLine_O7R26, VOf(Bf3));
    __hv_mul_f(VIf(Bf4), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_7hiGi, VOf(Bf4));
    __hv_mul_f(VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_var_f(&_c->sVarf_mEhBS, VOf(Bf3));
    __hv_mul_f(VIf(Bf4), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_SSqFv, VOf(Bf0));
    __hv_mul_f(VIf(Bf4), VIf(Bf0), VOf(Bf0));
    __hv_add_f(VIf(Bf3), VIf(O0), VOf(O0));
    __hv_add_f(VIf(Bf0), VIf(O1), VOf(O1));

    // save output vars to output buffer
    __hv_store_f(outputBuffers[0]+n, VIf(O0));
    __hv_store_f(outputBuffers[1]+n, VIf(O1));
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n4; // return the number of frames processed
}

int hv_slot0_process_inline(Hv_slot0 *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  int n = hv_slot0_process(c, bIn, bOut, n4);
  return n;
}

int hv_slot0_process_interleaved(Hv_slot0 *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = inputBuffers[i+numChannels*j];
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_slot0_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = bOut[i*n4+j];
    }
  }

  return n;
}

int hv_slot0_process_interleaved_short(Hv_slot0 *const c, short *const inputBuffers, short *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = ((float) inputBuffers[i+numChannels*j]) * 0.00003051757813f;
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_slot0_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = (short) (bOut[i*n4+j] * 32767.0f);
    }
  }

  return n;
}
