
/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER.
 */

/*
 * System Includes
 */

#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "Heavy_slot1.h"
#include "HvContext_slot1.h"
#include "HeavyMath.h"


/*
 * Function Declarations
 */
static void cBinop_PXK5I_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_dmXN1_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_bpe3k_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_GUnko_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_6QKM5_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_AEjVo_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_ghhCW_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_blf0i_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_I9QOG_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_9yMpR_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_2KUoE_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_FA34u_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_s81fB_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cDelay_MbsR2_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_gh9Cx_sendMessage(HvBase *, int, const HvMessage *const);
static void cPack_BExUd_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_Ocq77_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_JCiiB_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cBinop_YKLJB_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_b5YnN_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_ALjJc_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_zUOvS_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_cT4rk_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_AeJlV_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_dV1zd_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_khEh9_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_VAx35_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_rByiO_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_Cy6Sr_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_5lwBN_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_h12g4_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_kzEGI_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_FwRrh_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_XpCof_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_YOuxl_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(
    HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {
    case 0x18EDF2BD: { // w_amt
      ctx_scheduleMessage(_c, m, &cReceive_dV1zd_sendMessage, 0);
      break;
    }
    case 0x67E37CA3: { // __hv_notein
      ctx_scheduleMessage(_c, m, &cReceive_khEh9_sendMessage, 0);
      break;
    }
    case 0x5B29CFE0: { // w_freq
      ctx_scheduleMessage(_c, m, &cReceive_FwRrh_sendMessage, 0);
      break;
    }
    case 0x811CC33F: { // gain
      ctx_scheduleMessage(_c, m, &cReceive_kzEGI_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static struct HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {
    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

Hv_slot1 *hv_slot1_new_with_pool(double sampleRate, int poolKb) {
  hv_assert(sampleRate > 0.0); // can't initialise with sampling rate of 0
  hv_assert(poolKb >= 1); // a message pool of some reasonable size is always needed
  Hv_slot1 *const _c = (Hv_slot1 *) hv_malloc(sizeof(Hv_slot1));

  Base(_c)->numInputChannels = 0;
  Base(_c)->numOutputChannels = 2;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, poolKb);
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;
  Base(_c)->name = "slot1";

  Base(_c)->numBytes = sizeof(Hv_slot1);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_Gs1GI, 0.0f, sampleRate);
  Base(_c)->numBytes += sLine_init(&_c->sLine_vHi7m);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_9eDxl, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_6kFDB, 0.0f, sampleRate);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_bKNZg, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_5QeE6, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_fbdId, 0.0f, sampleRate);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_O33ga, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_bpe3k, 10.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_GUnko, 500.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_6QKM5, 1.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_blf0i, 10.0f);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_MbsR2, 10.0f);
  Base(_c)->numBytes += cPack_init(&_c->cPack_BExUd, 2);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_cT4rk, 1.0f); // __pow
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_VAx35, 0, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_rByiO, 2, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_Cy6Sr, 4, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_5lwBN, 1, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_h12g4, 3, 1);

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_I9QOG_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_YOuxl_sendMessage, 0);

  return _c;
}

Hv_slot1 *hv_slot1_new(double sampleRate) {
  return hv_slot1_new_with_pool(sampleRate, 10); // default to 10KB MessagePool
}

void hv_slot1_free(Hv_slot1 *_c) {
  cPack_free(&_c->cPack_BExUd);

  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}



/*
 * Static Function Implementation
 */
static void cBinop_PXK5I_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_5QeE6, m);
}

static void cMsg_dmXN1_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.5f);
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_Gs1GI, 1, m);
}

static void cVar_bpe3k_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_gh9Cx_sendMessage(_c, 0, m);
}

static void cVar_GUnko_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_ghhCW_sendMessage(_c, 0, m);
}

static void cVar_6QKM5_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cPack_onMessage(_c, &Context(_c)->cPack_BExUd, 0, m, &cPack_BExUd_sendMessage);
}

static void cMsg_AEjVo_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "stop");
  cSwitchcase_s81fB_onMessage(_c, NULL, 0, m, NULL);
}

static void cMsg_ghhCW_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.0f);
  msg_setElementToFrom(m, 1, n, 0);
  sLine_onMessage(_c, &Context(_c)->sLine_vHi7m, 0, m, NULL);
}

static void cVar_blf0i_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cPack_onMessage(_c, &Context(_c)->cPack_BExUd, 1, m, &cPack_BExUd_sendMessage);
}

static void cLoadbang_I9QOG_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_blf0i, 0, m, &cVar_blf0i_sendMessage);
}

static void cCast_9yMpR_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSwitchcase_s81fB_onMessage(_c, NULL, 0, m, NULL);
  cVar_onMessage(_c, &Context(_c)->cVar_bpe3k, 0, m, &cVar_bpe3k_sendMessage);
}

static void cCast_2KUoE_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_MbsR2, 0, m, &cDelay_MbsR2_sendMessage);
}

static void cMsg_FA34u_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "clear");
  cDelay_onMessage(_c, &Context(_c)->cDelay_MbsR2, 0, m, &cDelay_MbsR2_sendMessage);
}

static void cSwitchcase_s81fB_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x7A5B032D: { // "stop"
      cMsg_FA34u_sendMessage(_c, 0, m);
      break;
    }
    default: {
      cMsg_FA34u_sendMessage(_c, 0, m);
      cDelay_onMessage(_c, &Context(_c)->cDelay_MbsR2, 1, m, &cDelay_MbsR2_sendMessage);
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_2KUoE_sendMessage);
      break;
    }
  }
}

static void cDelay_MbsR2_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_MbsR2, m);
  cVar_onMessage(_c, &Context(_c)->cVar_6QKM5, 0, m, &cVar_6QKM5_sendMessage);
}

static void cMsg_gh9Cx_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  msg_setElementToFrom(m, 1, n, 0);
  sLine_onMessage(_c, &Context(_c)->sLine_vHi7m, 0, m, NULL);
}

static void cPack_BExUd_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sLine_onMessage(_c, &Context(_c)->sLine_vHi7m, 0, m, NULL);
}

static void cCast_Ocq77_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_AEjVo_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_GUnko, 0, m, &cVar_GUnko_sendMessage);
}

static void cSwitchcase_JCiiB_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_Ocq77_sendMessage);
      break;
    }
    default: {
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_9yMpR_sendMessage);
      break;
    }
  }
}

static void cBinop_YKLJB_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_bKNZg, m);
  cMsg_XpCof_sendMessage(_c, 0, m);
}

static void cBinop_b5YnN_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_cT4rk, HV_BINOP_POW, 1, m, &cBinop_cT4rk_sendMessage);
  cMsg_zUOvS_sendMessage(_c, 0, m);
}

static void cBinop_ALjJc_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_fbdId, 0, m);
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_Gs1GI, 0, m);
}

static void cMsg_zUOvS_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 2.0f);
  cBinop_onMessage(_c, &Context(_c)->cBinop_cT4rk, HV_BINOP_POW, 0, m, &cBinop_cT4rk_sendMessage);
}

static void cBinop_cT4rk_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 440.0f, 0, m, &cBinop_ALjJc_sendMessage);
}

static void cBinop_AeJlV_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 12.0f, 0, m, &cBinop_b5YnN_sendMessage);
}

static void cReceive_dV1zd_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 0.5f, 0, m, &cBinop_YKLJB_sendMessage);
}

static void cReceive_khEh9_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSlice_onMessage(_c, &Context(_c)->cSlice_Cy6Sr, 0, m, &cSlice_Cy6Sr_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_h12g4, 0, m, &cSlice_h12g4_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_rByiO, 0, m, &cSlice_rByiO_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_5lwBN, 0, m, &cSlice_5lwBN_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_VAx35, 0, m, &cSlice_VAx35_sendMessage);
}

static void cSlice_VAx35_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cSwitchcase_JCiiB_onMessage(_c, NULL, 0, m, NULL);
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_rByiO_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_Cy6Sr_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_5lwBN_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 69.0f, 0, m, &cBinop_AeJlV_sendMessage);
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_h12g4_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cReceive_kzEGI_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_O33ga, m);
  sVarf_onMessage(_c, &Context(_c)->sVarf_9eDxl, m);
}

static void cReceive_FwRrh_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_6kFDB, 0, m);
}

static void cMsg_XpCof_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  msg_setElementToFrom(m, 1, n, 0);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 0.0f, 0, m, &cBinop_PXK5I_sendMessage);
}

static void cLoadbang_YOuxl_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_dmXN1_sendMessage(_c, 0, m);
}




/*
 * Context Process Implementation
 */

int hv_slot1_process(Hv_slot1 *const _c, float **const inputBuffers, float **const outputBuffers, int nx) {
  const int n4 = nx & ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD

  // temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4, Bf5, Bf6;

  // input and output vars
  hv_bufferf_t O0, O1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; __hv_zero_f(VOf(ZERO));

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  for (int n = 0; n < n4; n += HV_N_SIMD) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

    

    // zero output buffers
    __hv_zero_f(VOf(O0));
    __hv_zero_f(VOf(O1));

    // process all signal functions
    __hv_phasor_k_f(&_c->sPhasor_Gs1GI, VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_k_f(VOf(Bf0), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf0));
    __hv_mul_f(VIf(Bf1), VIf(Bf0), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf3), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf4), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_sub_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_fma_f(VIf(Bf0), VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_line_f(&_c->sLine_vHi7m, VOf(Bf3));
    __hv_mul_f(VIf(Bf4), VIf(Bf3), VOf(Bf4));
    __hv_var_f(&_c->sVarf_9eDxl, VOf(Bf0));
    __hv_mul_f(VIf(Bf4), VIf(Bf0), VOf(Bf0));
    __hv_phasor_k_f(&_c->sPhasor_6kFDB, VOf(Bf4));
    __hv_var_k_f(VOf(Bf1), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf4), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_k_f(VOf(Bf4), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf1), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf4), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf4));
    __hv_mul_f(VIf(Bf1), VIf(Bf4), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf5), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf6), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf6), VOf(Bf6));
    __hv_sub_f(VIf(Bf1), VIf(Bf6), VOf(Bf6));
    __hv_fma_f(VIf(Bf4), VIf(Bf5), VIf(Bf6), VOf(Bf6));
    __hv_var_f(&_c->sVarf_bKNZg, VOf(Bf5));
    __hv_var_f(&_c->sVarf_5QeE6, VOf(Bf4));
    __hv_fma_f(VIf(Bf6), VIf(Bf5), VIf(Bf4), VOf(Bf4));
    __hv_mul_f(VIf(Bf0), VIf(Bf4), VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(O1), VOf(O1));
    __hv_phasor_k_f(&_c->sPhasor_fbdId, VOf(Bf0));
    __hv_var_k_f(VOf(Bf5), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf5), VOf(Bf5));
    __hv_abs_f(VIf(Bf5), VOf(Bf5));
    __hv_var_k_f(VOf(Bf0), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf5), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf5), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf5), VOf(Bf5));
    __hv_mul_f(VIf(Bf5), VIf(Bf5), VOf(Bf0));
    __hv_mul_f(VIf(Bf5), VIf(Bf0), VOf(Bf6));
    __hv_mul_f(VIf(Bf6), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf2), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf6), VIf(Bf2), VOf(Bf2));
    __hv_sub_f(VIf(Bf5), VIf(Bf2), VOf(Bf2));
    __hv_fma_f(VIf(Bf0), VIf(Bf1), VIf(Bf2), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_O33ga, VOf(Bf2));
    __hv_mul_f(VIf(Bf3), VIf(Bf2), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_add_f(VIf(Bf4), VIf(O0), VOf(O0));

    // save output vars to output buffer
    __hv_store_f(outputBuffers[0]+n, VIf(O0));
    __hv_store_f(outputBuffers[1]+n, VIf(O1));
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n4; // return the number of frames processed
}

int hv_slot1_process_inline(Hv_slot1 *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  int n = hv_slot1_process(c, bIn, bOut, n4);
  return n;
}

int hv_slot1_process_interleaved(Hv_slot1 *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = inputBuffers[i+numChannels*j];
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_slot1_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = bOut[i*n4+j];
    }
  }

  return n;
}

int hv_slot1_process_interleaved_short(Hv_slot1 *const c, short *const inputBuffers, short *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = ((float) inputBuffers[i+numChannels*j]) * 0.00003051757813f;
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_slot1_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = (short) (bOut[i*n4+j] * 32767.0f);
    }
  }

  return n;
}
