/**
 * Copyright (c) 2014,2015,2016 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER.
 */

#ifndef _HEAVYCONTEXT_SLOT1_H_
#define _HEAVYCONTEXT_SLOT1_H_

#include "HvBase.h"

#define Context(_x) ((Hv_slot1 *) (_x))

// object includes
#include "SignalVar.h"
#include "ControlCast.h"
#include "ControlSlice.h"
#include "SignalLine.h"
#include "ControlBinop.h"
#include "ControlVar.h"
#include "ControlDelay.h"
#include "HvMath.h"
#include "SignalPhasor.h"
#include "ControlPack.h"

typedef struct Hv_slot1 {
  HvBase base;

  // objects
  SignalPhasor sPhasor_JfQn8;
  SignalLine sLine_O0Rar;
  SignalVarf sVarf_rn0b3;
  SignalPhasor sPhasor_2Bnwz;
  SignalVarf sVarf_PcvAb;
  SignalVarf sVarf_d9lws;
  SignalPhasor sPhasor_qLhCd;
  SignalVarf sVarf_8lkZJ;
  ControlBinop cBinop_UtxaQ;
  ControlBinop cBinop_ZsvrY;
  ControlBinop cBinop_oDPKC;
  ControlBinop cBinop_YGxGe;
  ControlBinop cBinop_DmYox;
  ControlPack cPack_kgGkd;
  ControlDelay cDelay_x5wiJ;
  ControlVar cVar_qdGBS;
  ControlVar cVar_U8GVl;
  ControlVar cVar_3yBKP;
  ControlVar cVar_XpCxS;
  ControlSlice cSlice_P4mZO;
  ControlSlice cSlice_Q8b3A;
  ControlSlice cSlice_VNrLN;
  ControlSlice cSlice_BOmQ1;
  ControlSlice cSlice_c7DqY;
  ControlBinop cBinop_loirp;
} Hv_slot1;

#endif // _HEAVYCONTEXT_SLOT1_H_
