/**
 * Copyright (c) 2014,2015,2016 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER.
 */

#include "HvContext_slot1.h"
#include "HvMath.h"



/*
 * Function Declarations
 */
static void cBinop_UtxaQ_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_Y1Abc_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_ZsvrY_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_oDPKC_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_YGxGe_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_NM01c_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_5lJzq_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_DmYox_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_7O7CI_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_xQq5z_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_QXJny_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_c5Olt_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_j2ynF_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_qfAVn_sendMessage(HvBase *, int, const HvMessage *const);
static void cPack_kgGkd_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_v874A_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_otYiz_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_FOIO4_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cMsg_88GE7_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_x5wiJ_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_cbijn_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_qdGBS_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_D0D27_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_JqT0J_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cVar_U8GVl_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_3yBKP_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_XpCxS_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_cQOYc_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_P4mZO_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_Q8b3A_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_VNrLN_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_BOmQ1_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_c7DqY_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_loirp_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_jmidB_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(
    HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {
    case 0x18EDF2BD: { // w_amt
      ctx_scheduleMessage(_c, m, &cReceive_xQq5z_sendMessage, 0);
      break;
    }
    case 0x811CC33F: { // gain
      ctx_scheduleMessage(_c, m, &cReceive_QXJny_sendMessage, 0);
      break;
    }
    case 0x5B29CFE0: { // w_freq
      ctx_scheduleMessage(_c, m, &cReceive_jmidB_sendMessage, 0);
      break;
    }
    case 0x67E37CA3: { // __hv_notein
      ctx_scheduleMessage(_c, m, &cReceive_cQOYc_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static struct HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {
    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

#ifdef __cplusplus
extern "C" {
#endif
HV_EXPORT Hv_slot1 *hv_slot1_new_with_options(double sampleRate, int poolKb) {
  hv_assert(sampleRate > 0.0); // can't initialise with sampling rate of 0
  hv_assert(poolKb >= 1); // a message pool of some reasonable size is always needed
  Hv_slot1 *const _c = (Hv_slot1 *) hv_malloc(sizeof(Hv_slot1));

  Base(_c)->numInputChannels = 0;
  Base(_c)->numOutputChannels = 2;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, poolKb);
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;
  Base(_c)->name = "slot1";

  Base(_c)->numBytes = sizeof(Hv_slot1);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_JfQn8, 0.0f, sampleRate);
  Base(_c)->numBytes += sLine_init(&_c->sLine_O0Rar);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_rn0b3, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_2Bnwz, 0.0f, sampleRate);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_PcvAb, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_d9lws, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sPhasor_k_init(&_c->sPhasor_qLhCd, 0.0f, sampleRate);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_8lkZJ, 0.0f, 0.0f, false);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_ZsvrY, 1.0f); // __pow
  Base(_c)->numBytes += cPack_init(&_c->cPack_kgGkd, 2);
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_x5wiJ, 10.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_qdGBS, 500.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_U8GVl, 10.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_3yBKP, 10.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_XpCxS, 1.0f);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_P4mZO, 1, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_Q8b3A, 2, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_VNrLN, 4, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_BOmQ1, 3, 1);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_c7DqY, 0, 1);

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_v874A_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_5lJzq_sendMessage, 0);

  return _c;
}

HV_EXPORT Hv_slot1 *hv_slot1_new(double sampleRate) {
  return hv_slot1_new_with_options(sampleRate, 10); // default to 10KB MessagePool
}

HV_EXPORT void hv_slot1_free(Hv_slot1 *_c) {
  cPack_free(&_c->cPack_kgGkd);

  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}
#ifdef __cplusplus
}
#endif



/*
 * Static Function Implementation
 */
static void cBinop_UtxaQ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 12.0f, 0, m, &cBinop_YGxGe_sendMessage);
}

static void cMsg_Y1Abc_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 2.0f);
  cBinop_onMessage(_c, &Context(_c)->cBinop_ZsvrY, HV_BINOP_POW, 0, m, &cBinop_ZsvrY_sendMessage);
}

static void cBinop_ZsvrY_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 440.0f, 0, m, &cBinop_oDPKC_sendMessage);
}

static void cBinop_oDPKC_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_JfQn8, 0, m);
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_qLhCd, 0, m);
}

static void cBinop_YGxGe_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_ZsvrY, HV_BINOP_POW, 1, m, &cBinop_ZsvrY_sendMessage);
  cMsg_Y1Abc_sendMessage(_c, 0, m);
}

static void cMsg_NM01c_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  msg_setElementToFrom(m, 1, n, 0);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 0.0f, 0, m, &cBinop_loirp_sendMessage);
}

static void cLoadbang_5lJzq_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_7O7CI_sendMessage(_c, 0, m);
}

static void cBinop_DmYox_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_PcvAb, m);
  cMsg_NM01c_sendMessage(_c, 0, m);
}

static void cMsg_7O7CI_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.5f);
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_qLhCd, 1, m);
}

static void cReceive_xQq5z_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, 0.5f, 0, m, &cBinop_DmYox_sendMessage);
}

static void cReceive_QXJny_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_rn0b3, m);
  sVarf_onMessage(_c, &Context(_c)->sVarf_8lkZJ, m);
}

static void cMsg_c5Olt_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 1.0f);
  msg_setElementToFrom(m, 1, n, 0);
  sLine_onMessage(_c, &Context(_c)->sLine_O0Rar, 0, m, NULL);
}

static void cCast_j2ynF_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSwitchcase_FOIO4_onMessage(_c, NULL, 0, m, NULL);
  cVar_onMessage(_c, &Context(_c)->cVar_3yBKP, 0, m, &cVar_3yBKP_sendMessage);
}

static void cMsg_qfAVn_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(2);
  msg_init(m, 2, msg_getTimestamp(n));
  msg_setFloat(m, 0, 0.0f);
  msg_setElementToFrom(m, 1, n, 0);
  sLine_onMessage(_c, &Context(_c)->sLine_O0Rar, 0, m, NULL);
}

static void cPack_kgGkd_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sLine_onMessage(_c, &Context(_c)->sLine_O0Rar, 0, m, NULL);
}

static void cLoadbang_v874A_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_U8GVl, 0, m, &cVar_U8GVl_sendMessage);
}

static void cCast_otYiz_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_x5wiJ, 0, m, &cDelay_x5wiJ_sendMessage);
}

static void cSwitchcase_FOIO4_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x7A5B032D: { // "stop"
      cMsg_88GE7_sendMessage(_c, 0, m);
      break;
    }
    default: {
      cMsg_88GE7_sendMessage(_c, 0, m);
      cDelay_onMessage(_c, &Context(_c)->cDelay_x5wiJ, 1, m, &cDelay_x5wiJ_sendMessage);
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_otYiz_sendMessage);
      break;
    }
  }
}

static void cMsg_88GE7_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "clear");
  cDelay_onMessage(_c, &Context(_c)->cDelay_x5wiJ, 0, m, &cDelay_x5wiJ_sendMessage);
}

static void cDelay_x5wiJ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_x5wiJ, m);
  cVar_onMessage(_c, &Context(_c)->cVar_XpCxS, 0, m, &cVar_XpCxS_sendMessage);
}

static void cMsg_cbijn_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "stop");
  cSwitchcase_FOIO4_onMessage(_c, NULL, 0, m, NULL);
}

static void cVar_qdGBS_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_qfAVn_sendMessage(_c, 0, m);
}

static void cCast_D0D27_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_cbijn_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_qdGBS, 0, m, &cVar_qdGBS_sendMessage);
}

static void cSwitchcase_JqT0J_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_D0D27_sendMessage);
      break;
    }
    default: {
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_j2ynF_sendMessage);
      break;
    }
  }
}

static void cVar_U8GVl_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cPack_onMessage(_c, &Context(_c)->cPack_kgGkd, 1, m, &cPack_kgGkd_sendMessage);
}

static void cVar_3yBKP_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_c5Olt_sendMessage(_c, 0, m);
}

static void cVar_XpCxS_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cPack_onMessage(_c, &Context(_c)->cPack_kgGkd, 0, m, &cPack_kgGkd_sendMessage);
}

static void cReceive_cQOYc_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSlice_onMessage(_c, &Context(_c)->cSlice_VNrLN, 0, m, &cSlice_VNrLN_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_BOmQ1, 0, m, &cSlice_BOmQ1_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_Q8b3A, 0, m, &cSlice_Q8b3A_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_P4mZO, 0, m, &cSlice_P4mZO_sendMessage);
  cSlice_onMessage(_c, &Context(_c)->cSlice_c7DqY, 0, m, &cSlice_c7DqY_sendMessage);
}

static void cSlice_P4mZO_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 69.0f, 0, m, &cBinop_UtxaQ_sendMessage);
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_Q8b3A_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_VNrLN_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_BOmQ1_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSlice_c7DqY_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      cSwitchcase_JqT0J_onMessage(_c, NULL, 0, m, NULL);
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cBinop_loirp_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_d9lws, m);
}

static void cReceive_jmidB_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sPhasor_k_onMessage(_c, &Context(_c)->sPhasor_2Bnwz, 0, m);
}




/*
 * Context Process Implementation
 */

#ifdef __cplusplus
extern "C" {
#endif
HV_EXPORT int hv_slot1_process(Hv_slot1 *const _c, float **const inputBuffers, float **const outputBuffers, int nx) {
  const int n4 = nx & ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD

  // temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4, Bf5, Bf6;

  // input and output vars
  hv_bufferf_t O0, O1;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; __hv_zero_f(VOf(ZERO));

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  for (int n = 0; n < n4; n += HV_N_SIMD) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

    

    // zero output buffers
    __hv_zero_f(VOf(O0));
    __hv_zero_f(VOf(O1));

    // process all signal functions
    __hv_phasor_k_f(&_c->sPhasor_JfQn8, VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_k_f(VOf(Bf0), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf0));
    __hv_mul_f(VIf(Bf1), VIf(Bf0), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf3), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf4), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_sub_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_fma_f(VIf(Bf0), VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_line_f(&_c->sLine_O0Rar, VOf(Bf3));
    __hv_mul_f(VIf(Bf4), VIf(Bf3), VOf(Bf4));
    __hv_var_f(&_c->sVarf_rn0b3, VOf(Bf0));
    __hv_mul_f(VIf(Bf4), VIf(Bf0), VOf(Bf0));
    __hv_phasor_k_f(&_c->sPhasor_2Bnwz, VOf(Bf4));
    __hv_var_k_f(VOf(Bf1), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf4), VIf(Bf1), VOf(Bf1));
    __hv_abs_f(VIf(Bf1), VOf(Bf1));
    __hv_var_k_f(VOf(Bf4), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf1), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf1), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf4), VIf(Bf1), VOf(Bf1));
    __hv_mul_f(VIf(Bf1), VIf(Bf1), VOf(Bf4));
    __hv_mul_f(VIf(Bf1), VIf(Bf4), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf5), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf6), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf2), VIf(Bf6), VOf(Bf6));
    __hv_sub_f(VIf(Bf1), VIf(Bf6), VOf(Bf6));
    __hv_fma_f(VIf(Bf4), VIf(Bf5), VIf(Bf6), VOf(Bf6));
    __hv_var_f(&_c->sVarf_PcvAb, VOf(Bf5));
    __hv_var_f(&_c->sVarf_d9lws, VOf(Bf4));
    __hv_fma_f(VIf(Bf6), VIf(Bf5), VIf(Bf4), VOf(Bf4));
    __hv_mul_f(VIf(Bf0), VIf(Bf4), VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(O0), VOf(O0));
    __hv_phasor_k_f(&_c->sPhasor_qLhCd, VOf(Bf0));
    __hv_var_k_f(VOf(Bf5), 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0.5f, 0);
    __hv_sub_f(VIf(Bf0), VIf(Bf5), VOf(Bf5));
    __hv_abs_f(VIf(Bf5), VOf(Bf5));
    __hv_var_k_f(VOf(Bf0), 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0.25f, 0);
    __hv_sub_f(VIf(Bf5), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf5), 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 6.28319f, 0);
    __hv_mul_f(VIf(Bf0), VIf(Bf5), VOf(Bf5));
    __hv_mul_f(VIf(Bf5), VIf(Bf5), VOf(Bf0));
    __hv_mul_f(VIf(Bf5), VIf(Bf0), VOf(Bf6));
    __hv_mul_f(VIf(Bf6), VIf(Bf0), VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0.00784314f, 0);
    __hv_var_k_f(VOf(Bf2), 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0.166667f, 0);
    __hv_mul_f(VIf(Bf6), VIf(Bf2), VOf(Bf2));
    __hv_sub_f(VIf(Bf5), VIf(Bf2), VOf(Bf2));
    __hv_fma_f(VIf(Bf0), VIf(Bf1), VIf(Bf2), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_8lkZJ, VOf(Bf2));
    __hv_mul_f(VIf(Bf3), VIf(Bf2), VOf(Bf2));
    __hv_mul_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_add_f(VIf(Bf4), VIf(O1), VOf(O1));

    // save output vars to output buffer
    __hv_store_f(outputBuffers[0]+n, VIf(O0));
    __hv_store_f(outputBuffers[1]+n, VIf(O1));
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n4; // return the number of frames processed
}

HV_EXPORT int hv_slot1_process_inline(Hv_slot1 *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  int n = hv_slot1_process(c, bIn, bOut, n4);
  return n;
}

HV_EXPORT int hv_slot1_process_interleaved(Hv_slot1 *const c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = inputBuffers[i+numChannels*j];
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_slot1_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = bOut[i*n4+j];
    }
  }

  return n;
}

HV_EXPORT int hv_slot1_process_interleaved_short(Hv_slot1 *const c, short *const inputBuffers, short *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = ((float) inputBuffers[i+numChannels*j]) * 0.00003051757813f;
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_slot1_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = (short) (bOut[i*n4+j] * 32767.0f);
    }
  }

  return n;
}
#ifdef __cplusplus
}
#endif
